server:
  port: 8071

book-service:
  url: http://localhost:8081
  feign: /show

book-service-update:
  url: http://localhost:8070
  feign: /show

spring:
  devtools:
    add-properties: false
#  logging with zipkin and sleuth
  zipkin:
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      probability: 100

management:
  endpoint:
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  dashboard:
    proxy-stream-allow-list:
      - '*'

eureka:
  client:
    healthcheck:
      enabled: true

  instance:
    preferIpAddress: true
    hostname: localhost
    healthCheckUrl: https://${eureka.hostname}/health


