spring:
  cloud:
    stream:
      kafka:
        binder:
          auto-add-partitions: true
      bindings:
        input:
          destination: creationBookServiceDestination
          group: creationBookServiceGroup
          binder: kafka
        output:
          destination: storeBookServiceDestination
          group: storeBookServiceGroup
          binder: kafka

server:
  port: 8051

#  see @ConfigurationProperties("testProperty")
testProperty:
  field: 123456-dev