server:
  port: 8070

data:
  mongodb:
    uri: mongodb://localhost:27017/gallerydb

spring:
  data:
    mongodb:
      port: 27017
  #  logging with zipkin and sleuth
  zipkin:
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      probability: 100


