server:
  port: ${port:8081}

data:
  mongodb:
    uri: mongodb://localhost:27017/gallerydb

spring:
  data:
    mongodb:
      port: 27017

  cloud:
    config:
      # to customise server.port from environment settings
      override-system-properties: false